# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime
from enum import StrEnum
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  discord_id := <str>$discord_id,
  event := (
    delete calendar::GuildEvent
    filter .client = global client and .discord_id = discord_id
  ),
select event { ** }
"""


class ProjectionStatus(StrEnum):
    ONGOING = 'ONGOING'
    COMPLETED = 'COMPLETED'


class GuildEventDeleteResultClient(BaseModel):
    id: UUID
    password_hash: str
    username: str


class GuildEventDeleteResultProjection(BaseModel):
    id: UUID
    name: str
    status: ProjectionStatus
    channel_id: str
    message_id: str | None


class GuildEventDeleteResultParticipants(BaseModel):
    id: UUID
    discord_username: str
    discord_id: str


class GuildEventDeleteResultOrganizer(BaseModel):
    id: UUID
    discord_username: str
    discord_id: str


class GuildEventDeleteResult(BaseModel):
    discord_id: str
    url: str | None
    start_time: datetime
    name: str
    location: str | None
    image: str | None
    end_time: datetime
    description: str | None
    id: UUID
    organizer: GuildEventDeleteResultOrganizer
    participants: list[GuildEventDeleteResultParticipants]
    projection: GuildEventDeleteResultProjection | None
    client: GuildEventDeleteResultClient


adapter = TypeAdapter[GuildEventDeleteResult | None](GuildEventDeleteResult | None)


async def guild_event_delete(
    executor: AsyncIOExecutor,
    *,
    discord_id: str,
) -> GuildEventDeleteResult | None:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        discord_id=discord_id,
    )
    return adapter.validate_json(resp, strict=False)
