# Generated by gel-pydantic-codegen
# pyright: strict
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  discord_id := <str>$discord_id
delete calendar::UserCalendar
filter .user.discord_id = discord_id
"""


class UserCalendarDeleteResult(BaseModel):
    id: UUID


adapter = TypeAdapter[UserCalendarDeleteResult | None](UserCalendarDeleteResult | None)


async def user_calendar_delete(
    executor: AsyncIOExecutor,
    *,
    discord_id: str,
) -> UserCalendarDeleteResult | None:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        discord_id=discord_id,
    )
    return adapter.validate_json(resp, strict=False)
