# Generated by gel-pydantic-codegen
# pyright: strict
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  discord_id := <str>$discord_id,
  calendar := (select calendar::UserCalendar filter .user.discord_id = discord_id),
select assert_single(calendar) { ** }
"""


class UserCalendarSelectResultUser(BaseModel):
    discord_id: str
    discord_username: str
    id: UUID


class UserCalendarSelectResult(BaseModel):
    ics: str
    id: UUID
    user: UserCalendarSelectResultUser


adapter = TypeAdapter[UserCalendarSelectResult | None](UserCalendarSelectResult | None)


async def user_calendar_select(
    executor: AsyncIOExecutor,
    *,
    discord_id: str,
) -> UserCalendarSelectResult | None:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        discord_id=discord_id,
    )
    return adapter.validate_json(resp, strict=False)
