# Generated by gel-pydantic-codegen
# pyright: strict
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
select calendar::UserCalendar { ** }
"""


class UserCalendarSelectAllResultUser(BaseModel):
    id: UUID
    discord_id: str
    discord_username: str


class UserCalendarSelectAllResult(BaseModel):
    id: UUID
    ics: str
    user: UserCalendarSelectAllResultUser


adapter = TypeAdapter[list[UserCalendarSelectAllResult]](list[UserCalendarSelectAllResult])


async def user_calendar_select_all(
    executor: AsyncIOExecutor,
) -> list[UserCalendarSelectAllResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
    )
    return adapter.validate_json(resp, strict=False)
