# Generated by gel-pydantic-codegen
# pyright: strict

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  message_id := <str>$message_id,
select poll::Poll {
  message_id,
  channel_id,
  question,
  options: {
    rank,
    text,
    votes: {
      user: {
        discord_id,
      }
    }
  }
}
filter .message_id = message_id
"""


class PollGetByMessageIdResultOptionsVotesUser(BaseModel):
    discord_id: str


class PollGetByMessageIdResultOptionsVotes(BaseModel):
    user: PollGetByMessageIdResultOptionsVotesUser


class PollGetByMessageIdResultOptions(BaseModel):
    rank: int
    text: str
    votes: list[PollGetByMessageIdResultOptionsVotes]


class PollGetByMessageIdResult(BaseModel):
    channel_id: str
    message_id: str
    options: list[PollGetByMessageIdResultOptions]
    question: str


adapter = TypeAdapter[PollGetByMessageIdResult | None](PollGetByMessageIdResult | None)


async def poll_get_by_message_id(
    executor: AsyncIOExecutor,
    *,
    message_id: str,
) -> PollGetByMessageIdResult | None:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        message_id=message_id,
    )
    return adapter.validate_json(resp, strict=False)
