# Generated by gel-pydantic-codegen
# pyright: strict
from typing import Any
from uuid import UUID

import orjson
from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  message_id := <str>$message_id,
  channel_id := <str>$channel_id,
  question := <str>$question,
  options := <json>$options,
  _poll := (
    insert poll::Poll {
      client := global client,
      message_id := message_id,
      channel_id := channel_id,
      question := question,
    }
  ),
  _options := (
    for option in json_array_unpack(options) union (
      with
        rank := <int32>json_get(option, 'rank'),
        text := <str>json_get(option, 'text'),
      insert poll::Option {
        client := global client,
        rank := rank,
        text := text,
        poll := _poll
      }
    )
  ),
select { _poll, _options }
"""


class PollInsertResult(BaseModel):
    id: UUID


adapter = TypeAdapter[list[PollInsertResult]](list[PollInsertResult])


async def poll_insert(
    executor: AsyncIOExecutor,
    *,
    message_id: str,
    channel_id: str,
    question: str,
    options: Any,
) -> list[PollInsertResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        message_id=message_id,
        channel_id=channel_id,
        question=question,
        options=orjson.dumps(options).decode(),
    )
    return adapter.validate_json(resp, strict=False)
