# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime
from enum import StrEnum
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  id_al := <int32>$id_al,
  character := (select anilist::Character filter .id_al = id_al),
select waicolle::Player {
  *,
  user: {
    discord_id,
  },
}
filter .client = global client
and character in .tracked_characters
"""


class WaicolleGameMode(StrEnum):
    ALL = 'ALL'
    HUSBANDO = 'HUSBANDO'
    WAIFU = 'WAIFU'


class PlayerSelectByCharaResultUser(BaseModel):
    discord_id: str


class PlayerSelectByCharaResult(BaseModel):
    blood_shards: int
    frozen_at: datetime | None
    game_mode: WaicolleGameMode
    id: UUID
    moecoins: int
    user: PlayerSelectByCharaResultUser


adapter = TypeAdapter[list[PlayerSelectByCharaResult]](list[PlayerSelectByCharaResult])


async def player_select_by_chara(
    executor: AsyncIOExecutor,
    *,
    id_al: int,
) -> list[PlayerSelectByCharaResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        id_al=id_al,
    )
    return adapter.validate_json(resp, strict=False)
