# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime
from enum import StrEnum
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
select waicolle::Player {
  *,
  user: {
    discord_id,
  },
}
filter .client = global client
"""


class WaicolleGameMode(StrEnum):
    WAIFU = 'WAIFU'
    HUSBANDO = 'HUSBANDO'
    ALL = 'ALL'


class PlayerSelectAllResultUser(BaseModel):
    discord_id: str


class PlayerSelectAllResult(BaseModel):
    user: PlayerSelectAllResultUser
    id: UUID
    frozen_at: datetime | None
    blood_shards: int
    game_mode: WaicolleGameMode
    moecoins: int


adapter = TypeAdapter[list[PlayerSelectAllResult]](list[PlayerSelectAllResult])


async def player_select_all(
    executor: AsyncIOExecutor,
) -> list[PlayerSelectAllResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
    )
    return adapter.validate_json(resp, strict=False)
