# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime
from enum import StrEnum
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  discord_id := <str>$discord_id,
  player := (
    select waicolle::Player
    filter .client = global client and .user.discord_id = discord_id
  ),
select player {
  *,
  user: {
    discord_id,
    age_verified,
  },
}
"""


class WaicolleGameMode(StrEnum):
    ALL = 'ALL'
    HUSBANDO = 'HUSBANDO'
    WAIFU = 'WAIFU'


class PlayerGetByUserResultUser(BaseModel):
    age_verified: bool
    discord_id: str


class PlayerGetByUserResult(BaseModel):
    blood_shards: int
    frozen_at: datetime | None
    game_mode: WaicolleGameMode
    id: UUID
    moecoins: int
    user: PlayerGetByUserResultUser


adapter = TypeAdapter[PlayerGetByUserResult | None](PlayerGetByUserResult | None)


async def player_get_by_user(
    executor: AsyncIOExecutor,
    *,
    discord_id: str,
) -> PlayerGetByUserResult | None:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        discord_id=discord_id,
    )
    return adapter.validate_json(resp, strict=False)
