# Generated by gel-pydantic-codegen
# pyright: strict
from enum import StrEnum
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  discord_id := <str>$discord_id,
  player := (select waicolle::Player filter .client = global client and .user.discord_id = discord_id),
  id := <uuid>$id,
  collec := (select waicolle::Collection filter .id = id),
  charas := (
    select collec.characters
    filter any(.image_large not ilike '%/default.jpg')
  ),
  nb_charas := count(charas),
  owned := (
    select waicolle::Waifu
    filter .client = global client
    and .owner = assert_exists(player)
    and .character in charas
    and not .disabled
  ),
  owned_ids := (select owned.character.id_al),
  nb_owned := count(owned_ids),
select {
  collection := assert_exists(collec) {
    id,
    name,
    author: {
      user: {
        discord_id,
      },
    },
    medias := .items[is anilist::Media] {
      type,
      id_al,
      title_user_preferred,
    },
    staffs := .items[is anilist::Staff] {
      id_al,
      name_user_preferred,
      name_native,
    },
  },
  nb_charas := nb_charas,
  nb_owned := nb_owned,
}
"""


class AnilistMediaType(StrEnum):
    ANIME = 'ANIME'
    MANGA = 'MANGA'


class PlayerCollectionStatsResultCollectionStaffs(BaseModel):
    id_al: int
    name_native: str | None
    name_user_preferred: str


class PlayerCollectionStatsResultCollectionMedias(BaseModel):
    id_al: int
    title_user_preferred: str
    type: AnilistMediaType


class PlayerCollectionStatsResultCollectionAuthorUser(BaseModel):
    discord_id: str


class PlayerCollectionStatsResultCollectionAuthor(BaseModel):
    user: PlayerCollectionStatsResultCollectionAuthorUser


class PlayerCollectionStatsResultCollection(BaseModel):
    author: PlayerCollectionStatsResultCollectionAuthor
    id: UUID
    medias: list[PlayerCollectionStatsResultCollectionMedias]
    name: str
    staffs: list[PlayerCollectionStatsResultCollectionStaffs]


class PlayerCollectionStatsResult(BaseModel):
    collection: PlayerCollectionStatsResultCollection
    nb_charas: int
    nb_owned: int


adapter = TypeAdapter[PlayerCollectionStatsResult](PlayerCollectionStatsResult)


async def player_collection_stats(
    executor: AsyncIOExecutor,
    *,
    discord_id: str,
    id: UUID,
) -> PlayerCollectionStatsResult:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        discord_id=discord_id,
        id=id,
    )
    return adapter.validate_json(resp, strict=False)
