# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime
from enum import StrEnum
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
select waicolle::TradeOperation {
  *,
  author: {
    user: {
      discord_id,
    },
  },
  received: {
    *,
    character: { id_al },
    owner: {
      user: {
        discord_id,
      },
    },
    original_owner: {
      user: {
        discord_id,
      },
    },
    custom_position_waifu: { id },
  },
  offeree: {
    user: {
      discord_id,
    },
  },
  offered: {
    *,
    character: { id_al },
    owner: {
      user: {
        discord_id,
      },
    },
    original_owner: {
      user: {
        discord_id,
      },
    },
    custom_position_waifu: { id },
  },
}
filter .client = global client
and not exists .completed_at
"""


class WaicolleCollagePosition(StrEnum):
    DEFAULT = 'DEFAULT'
    LEFT_OF = 'LEFT_OF'
    RIGHT_OF = 'RIGHT_OF'


class TradeSelectResultReceivedOwnerUser(BaseModel):
    discord_id: str


class TradeSelectResultReceivedOwner(BaseModel):
    user: TradeSelectResultReceivedOwnerUser


class TradeSelectResultReceivedOriginalOwnerUser(BaseModel):
    discord_id: str


class TradeSelectResultReceivedOriginalOwner(BaseModel):
    user: TradeSelectResultReceivedOriginalOwnerUser


class TradeSelectResultReceivedCustomPositionWaifu(BaseModel):
    id: UUID


class TradeSelectResultReceivedCharacter(BaseModel):
    id_al: int


class TradeSelectResultReceived(BaseModel):
    blooded: bool
    character: TradeSelectResultReceivedCharacter
    custom_collage: bool
    custom_image: str | None
    custom_name: str | None
    custom_position: WaicolleCollagePosition
    custom_position_waifu: TradeSelectResultReceivedCustomPositionWaifu | None
    disabled: bool
    frozen: bool
    id: UUID
    level: int
    locked: bool
    nanaed: bool
    original_owner: TradeSelectResultReceivedOriginalOwner | None
    owner: TradeSelectResultReceivedOwner
    timestamp: datetime
    trade_locked: bool


class TradeSelectResultOffereeUser(BaseModel):
    discord_id: str


class TradeSelectResultOfferee(BaseModel):
    user: TradeSelectResultOffereeUser


class TradeSelectResultOfferedOwnerUser(BaseModel):
    discord_id: str


class TradeSelectResultOfferedOwner(BaseModel):
    user: TradeSelectResultOfferedOwnerUser


class TradeSelectResultOfferedOriginalOwnerUser(BaseModel):
    discord_id: str


class TradeSelectResultOfferedOriginalOwner(BaseModel):
    user: TradeSelectResultOfferedOriginalOwnerUser


class TradeSelectResultOfferedCustomPositionWaifu(BaseModel):
    id: UUID


class TradeSelectResultOfferedCharacter(BaseModel):
    id_al: int


class TradeSelectResultOffered(BaseModel):
    blooded: bool
    character: TradeSelectResultOfferedCharacter
    custom_collage: bool
    custom_image: str | None
    custom_name: str | None
    custom_position: WaicolleCollagePosition
    custom_position_waifu: TradeSelectResultOfferedCustomPositionWaifu | None
    disabled: bool
    frozen: bool
    id: UUID
    level: int
    locked: bool
    nanaed: bool
    original_owner: TradeSelectResultOfferedOriginalOwner | None
    owner: TradeSelectResultOfferedOwner
    timestamp: datetime
    trade_locked: bool


class TradeSelectResultAuthorUser(BaseModel):
    discord_id: str


class TradeSelectResultAuthor(BaseModel):
    user: TradeSelectResultAuthorUser


class TradeSelectResult(BaseModel):
    author: TradeSelectResultAuthor
    blood_shards: int
    completed_at: datetime | None
    created_at: datetime
    id: UUID
    offered: list[TradeSelectResultOffered]
    offeree: TradeSelectResultOfferee
    received: list[TradeSelectResultReceived]


adapter = TypeAdapter[list[TradeSelectResult]](list[TradeSelectResult])


async def trade_select(
    executor: AsyncIOExecutor,
) -> list[TradeSelectResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
    )
    return adapter.validate_json(resp, strict=False)
