# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime
from enum import StrEnum
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  ids := <array<uuid>>$ids,
  locked := <optional bool>$locked,
  blooded := <optional bool>$blooded,
  nanaed := <optional bool>$nanaed,
  level := <optional int32>$level,
  custom_collage := <optional bool>$custom_collage,
  timestamp := <optional datetime>$timestamp,
  updated := (
    update waicolle::Waifu
    filter .id in array_unpack(ids)
    set {
      locked := locked ?? .locked,
      blooded := blooded ?? .blooded,
      nanaed := nanaed ?? .nanaed,
      level := level ?? .level,
      custom_collage := custom_collage ?? .custom_collage,
      timestamp := timestamp ?? .timestamp,
    }
  )
select updated {
  *,
  character: { id_al },
  owner: {
    user: {
      discord_id,
    },
  },
  original_owner: {
    user: {
      discord_id,
    },
  },
  custom_position_waifu: { id },
}
"""


class WaicolleCollagePosition(StrEnum):
    DEFAULT = 'DEFAULT'
    LEFT_OF = 'LEFT_OF'
    RIGHT_OF = 'RIGHT_OF'


class WaifuBulkUpdateResultOwnerUser(BaseModel):
    discord_id: str


class WaifuBulkUpdateResultOwner(BaseModel):
    user: WaifuBulkUpdateResultOwnerUser


class WaifuBulkUpdateResultOriginalOwnerUser(BaseModel):
    discord_id: str


class WaifuBulkUpdateResultOriginalOwner(BaseModel):
    user: WaifuBulkUpdateResultOriginalOwnerUser


class WaifuBulkUpdateResultCustomPositionWaifu(BaseModel):
    id: UUID


class WaifuBulkUpdateResultCharacter(BaseModel):
    id_al: int


class WaifuBulkUpdateResult(BaseModel):
    blooded: bool
    character: WaifuBulkUpdateResultCharacter
    custom_collage: bool
    custom_image: str | None
    custom_name: str | None
    custom_position: WaicolleCollagePosition
    custom_position_waifu: WaifuBulkUpdateResultCustomPositionWaifu | None
    disabled: bool
    frozen: bool
    id: UUID
    level: int
    locked: bool
    nanaed: bool
    original_owner: WaifuBulkUpdateResultOriginalOwner | None
    owner: WaifuBulkUpdateResultOwner
    timestamp: datetime
    trade_locked: bool


adapter = TypeAdapter[list[WaifuBulkUpdateResult]](list[WaifuBulkUpdateResult])


async def waifu_bulk_update(
    executor: AsyncIOExecutor,
    *,
    ids: list[UUID],
    locked: bool | None = None,
    blooded: bool | None = None,
    nanaed: bool | None = None,
    level: int | None = None,
    custom_collage: bool | None = None,
    timestamp: datetime | None = None,
) -> list[WaifuBulkUpdateResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        ids=ids,
        locked=locked,
        blooded=blooded,
        nanaed=nanaed,
        level=level,
        custom_collage=custom_collage,
        timestamp=timestamp,
    )
    return adapter.validate_json(resp, strict=False)
