# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  players := (select waicolle::Player filter .client = global client),
  waifus := (select waicolle::Waifu filter .client = global client and not .disabled),
  charas := (select anilist::Character filter .id_al in waifus.character.id_al),
select {
  players := players {
    discord_id := .user.discord_id,
    discord_username := .user.discord_username,
    tracked := .tracked_characters.id_al
  },
  waifus := waifus {
    id,
    character_id := .character.id_al,
    owner_discord_id := .owner.user.discord_id,
    original_owner_discord_id := .original_owner.user.discord_id,
    timestamp,
    level,
    locked,
    nanaed,
    blooded,
    trade_locked,
  },
  charas := charas {
    id_al,
    image := str_split(.image_large, '/')[-1],
    favourites,
  },
}
"""


class WaifuExportResultWaifus(BaseModel):
    blooded: bool
    character_id: int
    id: UUID
    level: int
    locked: bool
    nanaed: bool
    original_owner_discord_id: str | None
    owner_discord_id: str
    timestamp: datetime
    trade_locked: bool


class WaifuExportResultPlayers(BaseModel):
    discord_id: str
    discord_username: str
    tracked: list[int]


class WaifuExportResultCharas(BaseModel):
    favourites: int
    id_al: int
    image: str


class WaifuExportResult(BaseModel):
    charas: list[WaifuExportResultCharas]
    players: list[WaifuExportResultPlayers]
    waifus: list[WaifuExportResultWaifus]


adapter = TypeAdapter[WaifuExportResult](WaifuExportResult)


async def waifu_export(
    executor: AsyncIOExecutor,
) -> WaifuExportResult:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
    )
    return adapter.validate_json(resp, strict=False)
