# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime
from enum import StrEnum
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  discord_id := <str>$discord_id,
  player := (select waicolle::Player filter .client = global client and .user.discord_id = discord_id),
  waifus := (
    select waicolle::Waifu
    filter .client = global client
    and .owner = assert_exists(player)
    and not .trade_locked and not .blooded
    and not .disabled
  ),
  grouped := (
    group waifus
    using chara_id_al := .character.id_al
    by chara_id_al, .level
  ),
  counted := (
    select grouped {
      count := count(.elements),
    }
  ),
select counted {
  key: { chara_id_al, level },
  grouping,
  elements: {
    *,
    character: { id_al },
    owner: {
      user: {
        discord_id,
      },
    },
    original_owner: {
      user: {
        discord_id,
      },
    },
    custom_position_waifu: { id },
  } order by .timestamp desc
}
filter .count >= 4
"""


class WaicolleCollagePosition(StrEnum):
    DEFAULT = 'DEFAULT'
    LEFT_OF = 'LEFT_OF'
    RIGHT_OF = 'RIGHT_OF'


class WaifuAscendableResultKey(BaseModel):
    chara_id_al: int
    level: int


class WaifuAscendableResultElementsOwnerUser(BaseModel):
    discord_id: str


class WaifuAscendableResultElementsOwner(BaseModel):
    user: WaifuAscendableResultElementsOwnerUser


class WaifuAscendableResultElementsOriginalOwnerUser(BaseModel):
    discord_id: str


class WaifuAscendableResultElementsOriginalOwner(BaseModel):
    user: WaifuAscendableResultElementsOriginalOwnerUser


class WaifuAscendableResultElementsCustomPositionWaifu(BaseModel):
    id: UUID


class WaifuAscendableResultElementsCharacter(BaseModel):
    id_al: int


class WaifuAscendableResultElements(BaseModel):
    blooded: bool
    character: WaifuAscendableResultElementsCharacter
    custom_collage: bool
    custom_image: str | None
    custom_name: str | None
    custom_position: WaicolleCollagePosition
    custom_position_waifu: WaifuAscendableResultElementsCustomPositionWaifu | None
    disabled: bool
    frozen: bool
    id: UUID
    level: int
    locked: bool
    nanaed: bool
    original_owner: WaifuAscendableResultElementsOriginalOwner | None
    owner: WaifuAscendableResultElementsOwner
    timestamp: datetime
    trade_locked: bool


class WaifuAscendableResult(BaseModel):
    elements: list[WaifuAscendableResultElements]
    grouping: list[str]
    key: WaifuAscendableResultKey


adapter = TypeAdapter[list[WaifuAscendableResult]](list[WaifuAscendableResult])


async def waifu_ascendable(
    executor: AsyncIOExecutor,
    *,
    discord_id: str,
) -> list[WaifuAscendableResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        discord_id=discord_id,
    )
    return adapter.validate_json(resp, strict=False)
