# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime
from enum import StrEnum
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  discord_id := <str>$discord_id,
  charas_ids := <array<int32>>$charas_ids,
  player := (select waicolle::Player filter .client = global client and .user.discord_id = discord_id),
for id_al in array_unpack(charas_ids) union (
  with
    chara := (select anilist::Character filter .id_al = id_al),
    inserted := (
      insert waicolle::Waifu {
        client := global client,
        character := chara,
        owner := player,
        original_owner := player,
      }
    ),
  select inserted {
    *,
    character: { id_al },
    owner: {
      user: {
        discord_id,
      },
    },
    original_owner: {
      user: {
        discord_id,
      },
    },
    custom_position_waifu: { id },
  }
)
"""


class WaicolleCollagePosition(StrEnum):
    DEFAULT = 'DEFAULT'
    LEFT_OF = 'LEFT_OF'
    RIGHT_OF = 'RIGHT_OF'


class WaifuInsertResultOwnerUser(BaseModel):
    discord_id: str


class WaifuInsertResultOwner(BaseModel):
    user: WaifuInsertResultOwnerUser


class WaifuInsertResultOriginalOwnerUser(BaseModel):
    discord_id: str


class WaifuInsertResultOriginalOwner(BaseModel):
    user: WaifuInsertResultOriginalOwnerUser


class WaifuInsertResultCustomPositionWaifu(BaseModel):
    id: UUID


class WaifuInsertResultCharacter(BaseModel):
    id_al: int


class WaifuInsertResult(BaseModel):
    blooded: bool
    character: WaifuInsertResultCharacter
    custom_collage: bool
    custom_image: str | None
    custom_name: str | None
    custom_position: WaicolleCollagePosition
    custom_position_waifu: WaifuInsertResultCustomPositionWaifu | None
    disabled: bool
    frozen: bool
    id: UUID
    level: int
    locked: bool
    nanaed: bool
    original_owner: WaifuInsertResultOriginalOwner | None
    owner: WaifuInsertResultOwner
    timestamp: datetime
    trade_locked: bool


adapter = TypeAdapter[list[WaifuInsertResult]](list[WaifuInsertResult])


async def waifu_insert(
    executor: AsyncIOExecutor,
    *,
    discord_id: str,
    charas_ids: list[int],
) -> list[WaifuInsertResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        discord_id=discord_id,
        charas_ids=charas_ids,
    )
    return adapter.validate_json(resp, strict=False)
