# Generated by gel-pydantic-codegen
# pyright: strict
from enum import StrEnum

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  id_al := <int32>$id_al,
select anilist::CharacterEdge {
  character_role,
  media: {
    id_al,
    favourites,
    site_url,
    type,
    id_mal,
    title_user_preferred,
    title_native,
    title_english,
    synonyms,
    description,
    status,
    season,
    season_year,
    episodes,
    duration,
    chapters,
    cover_image_extra_large,
    cover_image_color,
    popularity,
    is_adult,
    genres,
  },
  voice_actors: {
    id_al,
    favourites,
    site_url,
    name_user_preferred,
    name_native,
    name_alternative,
    description,
    image_large,
    gender,
    age,
    date_of_birth_year,
    date_of_birth_month,
    date_of_birth_day,
    date_of_death_year,
    date_of_death_month,
    date_of_death_day,
  } order by .favourites desc
}
filter .character.id_al = id_al
order by .media.popularity desc
"""


class AnilistCharacterRole(StrEnum):
    BACKGROUND = 'BACKGROUND'
    MAIN = 'MAIN'
    SUPPORTING = 'SUPPORTING'


class AnilistMediaSeason(StrEnum):
    FALL = 'FALL'
    SPRING = 'SPRING'
    SUMMER = 'SUMMER'
    WINTER = 'WINTER'


class AnilistMediaStatus(StrEnum):
    CANCELLED = 'CANCELLED'
    FINISHED = 'FINISHED'
    HIATUS = 'HIATUS'
    NOT_YET_RELEASED = 'NOT_YET_RELEASED'
    RELEASING = 'RELEASING'


class AnilistMediaType(StrEnum):
    ANIME = 'ANIME'
    MANGA = 'MANGA'


class CEdgeSelectFilterCharaResultVoiceActors(BaseModel):
    age: int | None
    date_of_birth_day: int | None
    date_of_birth_month: int | None
    date_of_birth_year: int | None
    date_of_death_day: int | None
    date_of_death_month: int | None
    date_of_death_year: int | None
    description: str | None
    favourites: int
    gender: str | None
    id_al: int
    image_large: str
    name_alternative: list[str]
    name_native: str | None
    name_user_preferred: str
    site_url: str


class CEdgeSelectFilterCharaResultMedia(BaseModel):
    chapters: int | None
    cover_image_color: str | None
    cover_image_extra_large: str
    description: str | None
    duration: int | None
    episodes: int | None
    favourites: int
    genres: list[str]
    id_al: int
    id_mal: int | None
    is_adult: bool
    popularity: int
    season: AnilistMediaSeason | None
    season_year: int | None
    site_url: str
    status: AnilistMediaStatus | None
    synonyms: list[str]
    title_english: str | None
    title_native: str | None
    title_user_preferred: str
    type: AnilistMediaType


class CEdgeSelectFilterCharaResult(BaseModel):
    character_role: AnilistCharacterRole
    media: CEdgeSelectFilterCharaResultMedia
    voice_actors: list[CEdgeSelectFilterCharaResultVoiceActors]


adapter = TypeAdapter[list[CEdgeSelectFilterCharaResult]](list[CEdgeSelectFilterCharaResult])


async def c_edge_select_filter_chara(
    executor: AsyncIOExecutor,
    *,
    id_al: int,
) -> list[CEdgeSelectFilterCharaResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        id_al=id_al,
    )
    return adapter.validate_json(resp, strict=False)
