# Generated by gel-pydantic-codegen
# pyright: strict
from enum import StrEnum

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
select anilist::Character {
  id_al,
  favourites,
  site_url,
  name_user_preferred,
  name_alternative,
  name_alternative_spoiler,
  name_native,
  description,
  image_large,
  gender,
  age,
  date_of_birth_year,
  date_of_birth_month,
  date_of_birth_day,
  rank,
  fuzzy_gender,
}
order by random()
limit 1
"""


class WaicolleRank(StrEnum):
    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'
    E = 'E'
    S = 'S'


class CharaGetRandomResult(BaseModel):
    age: str | None
    date_of_birth_day: int | None
    date_of_birth_month: int | None
    date_of_birth_year: int | None
    description: str | None
    favourites: int
    fuzzy_gender: str | None
    gender: str | None
    id_al: int
    image_large: str
    name_alternative: list[str]
    name_alternative_spoiler: list[str]
    name_native: str | None
    name_user_preferred: str
    rank: WaicolleRank
    site_url: str


adapter = TypeAdapter[CharaGetRandomResult | None](CharaGetRandomResult | None)


async def chara_get_random(
    executor: AsyncIOExecutor,
) -> CharaGetRandomResult | None:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
    )
    return adapter.validate_json(resp, strict=False)
