# Generated by gel-pydantic-codegen
# pyright: strict
from enum import StrEnum
from typing import Literal

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  media_type := <optional anilist::MediaType>$media_type,
  discord_id := <optional str>$discord_id,
  entries := (
    (select anilist::Entry filter .account.user.discord_id = discord_id)
    if (exists discord_id) else
    (select anilist::Entry)
  ),
select entries {
  status,
  progress,
  score,
  media: {
    id_al,
  },
  account: {
    user: {
      discord_id,
    },
  }
}
filter .media.type = media_type if exists media_type else true
"""


ENTRY_SELECT_ALL_MEDIA_TYPE = Literal[
    'ANIME',
    'MANGA',
]


class AnilistEntryStatus(StrEnum):
    COMPLETED = 'COMPLETED'
    CURRENT = 'CURRENT'
    DROPPED = 'DROPPED'
    PAUSED = 'PAUSED'
    PLANNING = 'PLANNING'
    REPEATING = 'REPEATING'


class EntrySelectAllResultMedia(BaseModel):
    id_al: int


class EntrySelectAllResultAccountUser(BaseModel):
    discord_id: str


class EntrySelectAllResultAccount(BaseModel):
    user: EntrySelectAllResultAccountUser


class EntrySelectAllResult(BaseModel):
    account: EntrySelectAllResultAccount
    media: EntrySelectAllResultMedia
    progress: int
    score: float
    status: AnilistEntryStatus


adapter = TypeAdapter[list[EntrySelectAllResult]](list[EntrySelectAllResult])


async def entry_select_all(
    executor: AsyncIOExecutor,
    *,
    media_type: ENTRY_SELECT_ALL_MEDIA_TYPE | None = None,
    discord_id: str | None = None,
) -> list[EntrySelectAllResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        media_type=media_type,
        discord_id=discord_id,
    )
    return adapter.validate_json(resp, strict=False)
