# Generated by gel-pydantic-codegen
# pyright: strict
from enum import StrEnum

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  id_al := <int32>$id_al,
select anilist::Entry {
  status,
  progress,
  score,
  account: {
    user: {
      discord_id,
    },
  }
}
filter .media.id_al = id_al
"""


class AnilistEntryStatus(StrEnum):
    COMPLETED = 'COMPLETED'
    CURRENT = 'CURRENT'
    DROPPED = 'DROPPED'
    PAUSED = 'PAUSED'
    PLANNING = 'PLANNING'
    REPEATING = 'REPEATING'


class EntrySelectFilterMediaResultAccountUser(BaseModel):
    discord_id: str


class EntrySelectFilterMediaResultAccount(BaseModel):
    user: EntrySelectFilterMediaResultAccountUser


class EntrySelectFilterMediaResult(BaseModel):
    account: EntrySelectFilterMediaResultAccount
    progress: int
    score: float
    status: AnilistEntryStatus


adapter = TypeAdapter[list[EntrySelectFilterMediaResult]](list[EntrySelectFilterMediaResult])


async def entry_select_filter_media(
    executor: AsyncIOExecutor,
    *,
    id_al: int,
) -> list[EntrySelectFilterMediaResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        id_al=id_al,
    )
    return adapter.validate_json(resp, strict=False)
