# Generated by gel-pydantic-codegen
# pyright: strict
from enum import StrEnum

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  ids_al := <array<int32>>$ids_al
select anilist::Media {
  id_al,
  favourites,
  site_url,
  type,
  id_mal,
  title_user_preferred,
  title_native,
  title_english,
  synonyms,
  description,
  status,
  season,
  season_year,
  episodes,
  duration,
  chapters,
  cover_image_extra_large,
  cover_image_color,
  popularity,
  is_adult,
  genres,
} filter .id_al in array_unpack(ids_al)
"""


class AnilistMediaSeason(StrEnum):
    FALL = 'FALL'
    SPRING = 'SPRING'
    SUMMER = 'SUMMER'
    WINTER = 'WINTER'


class AnilistMediaStatus(StrEnum):
    CANCELLED = 'CANCELLED'
    FINISHED = 'FINISHED'
    HIATUS = 'HIATUS'
    NOT_YET_RELEASED = 'NOT_YET_RELEASED'
    RELEASING = 'RELEASING'


class AnilistMediaType(StrEnum):
    ANIME = 'ANIME'
    MANGA = 'MANGA'


class MediaSelectResult(BaseModel):
    chapters: int | None
    cover_image_color: str | None
    cover_image_extra_large: str
    description: str | None
    duration: int | None
    episodes: int | None
    favourites: int
    genres: list[str]
    id_al: int
    id_mal: int | None
    is_adult: bool
    popularity: int
    season: AnilistMediaSeason | None
    season_year: int | None
    site_url: str
    status: AnilistMediaStatus | None
    synonyms: list[str]
    title_english: str | None
    title_native: str | None
    title_user_preferred: str
    type: AnilistMediaType


adapter = TypeAdapter[list[MediaSelectResult]](list[MediaSelectResult])


async def media_select(
    executor: AsyncIOExecutor,
    *,
    ids_al: list[int],
) -> list[MediaSelectResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        ids_al=ids_al,
    )
    return adapter.validate_json(resp, strict=False)
