# Generated by gel-pydantic-codegen
# pyright: strict
from enum import StrEnum

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
select anilist::Media {
  id_al,
  type,
  title_user_preferred,
  title_native,
  title_english,
  synonyms,
}
order by .favourites desc
"""


class AnilistMediaType(StrEnum):
    ANIME = 'ANIME'
    MANGA = 'MANGA'


class MediaSelectAllTitlesResult(BaseModel):
    id_al: int
    synonyms: list[str]
    title_english: str | None
    title_native: str | None
    title_user_preferred: str
    type: AnilistMediaType


adapter = TypeAdapter[list[MediaSelectAllTitlesResult]](list[MediaSelectAllTitlesResult])


async def media_select_all_titles(
    executor: AsyncIOExecutor,
) -> list[MediaSelectAllTitlesResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
    )
    return adapter.validate_json(resp, strict=False)
