# Generated by gel-pydantic-codegen
# pyright: strict

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
select anilist::Tag {
  id_al,
  name,
  description,
  category,
  is_adult,
}
"""


class TagSelectResult(BaseModel):
    category: str
    description: str
    id_al: int
    is_adult: bool
    name: str


adapter = TypeAdapter[list[TagSelectResult]](list[TagSelectResult])


async def tag_select(
    executor: AsyncIOExecutor,
) -> list[TagSelectResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
    )
    return adapter.validate_json(resp, strict=False)
