# Generated by gel-pydantic-codegen
# pyright: strict
from enum import StrEnum
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
select presence::Presence { id, type, name }
filter .client = global client
"""


class PresencePresenceType(StrEnum):
    LISTENING = 'LISTENING'
    PLAYING = 'PLAYING'
    WATCHING = 'WATCHING'


class PresenceSelectAllResult(BaseModel):
    id: UUID
    name: str
    type: PresencePresenceType


adapter = TypeAdapter[list[PresenceSelectAllResult]](list[PresenceSelectAllResult])


async def presence_select_all(
    executor: AsyncIOExecutor,
) -> list[PresenceSelectAllResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
    )
    return adapter.validate_json(resp, strict=False)
