# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  channel_id := <optional str>$channel_id,
  guild_id := <optional str>$guild_id,
  start_date := <optional datetime>$start_date,
  end_date := <optional datetime>$end_date,
select discord::Message {
  content,
  channel_id,
  guild_id,
  author_id,
  timestamp,
}
filter
  (.channel_id = channel_id if exists channel_id else true) and
  (.guild_id = guild_id if exists guild_id else true) and
  (.timestamp >= start_date if exists start_date else true) and
  (.timestamp <= end_date if exists end_date else true) and
  not exists .deleted_at and
  not exists .noindex and
  len(.content) > 0
order by .timestamp desc
"""


class MessageWordFrequencyResult(BaseModel):
    content: str
    channel_id: str
    guild_id: str | None
    author_id: str
    timestamp: datetime


adapter = TypeAdapter[list[MessageWordFrequencyResult]](list[MessageWordFrequencyResult])


async def message_word_frequency(
    executor: AsyncIOExecutor,
    *,
    channel_id: str | None = None,
    guild_id: str | None = None,
    start_date: datetime | None = None,
    end_date: datetime | None = None,
) -> list[MessageWordFrequencyResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        channel_id=channel_id,
        guild_id=guild_id,
        start_date=start_date,
        end_date=end_date,
    )
    return adapter.validate_json(resp, strict=False)
