# Generated by gel-pydantic-codegen
# pyright: strict
from typing import Any
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  items := <array <json>>$items,
for item in array_unpack(items)
union (
  with
    message_id := <str>json_get(item, 'message_id'),
    noindex := <str>json_get(item, 'noindex'),
  update discord::Message
  filter .client = global client and .message_id = message_id
  set {
    noindex := noindex if noindex != '' else {}
  }
)
"""


class MessageBulkUpdateNoindexResult(BaseModel):
    id: UUID


adapter = TypeAdapter[list[MessageBulkUpdateNoindexResult]](list[MessageBulkUpdateNoindexResult])


async def message_bulk_update_noindex(
    executor: AsyncIOExecutor,
    *,
    items: list[Any],
) -> list[MessageBulkUpdateNoindexResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        items=items,
    )
    return adapter.validate_json(resp, strict=False)
