# Generated by gel-pydantic-codegen
# pyright: strict
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  message_ids := <array<str>>$message_ids,
update discord::Message
filter .client = global client
and .message_id in array_unpack(message_ids)
and not exists(.deleted_at)
set {
  deleted_at := datetime_of_transaction(),
}
"""


class MessageBulkDeleteResult(BaseModel):
    id: UUID


adapter = TypeAdapter[list[MessageBulkDeleteResult]](list[MessageBulkDeleteResult])


async def message_bulk_delete(
    executor: AsyncIOExecutor,
    *,
    message_ids: list[str],
) -> list[MessageBulkDeleteResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        message_ids=message_ids,
    )
    return adapter.validate_json(resp, strict=False)
