# Generated by gel-pydantic-codegen
# pyright: strict
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  message_id := <str>$message_id,
  noindex := <str>$noindex,
update discord::Message
filter .client = global client and .message_id = message_id
set {
  noindex := noindex if noindex != '' else {}
}
"""


class MessageUpdateNoindexResult(BaseModel):
    id: UUID


adapter = TypeAdapter[MessageUpdateNoindexResult | None](MessageUpdateNoindexResult | None)


async def message_update_noindex(
    executor: AsyncIOExecutor,
    *,
    message_id: str,
    noindex: str,
) -> MessageUpdateNoindexResult | None:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        message_id=message_id,
        noindex=noindex,
    )
    return adapter.validate_json(resp, strict=False)
