# Generated by gel-pydantic-codegen
# pyright: strict
from typing import Any
from uuid import UUID

import orjson
from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  message_id := <str>$message_id,
  data := <json>$data,
insert discord::Message {
  client := global client,
  data := data,
  guild_id := <str>json_get(data, 'guild_id'),
  channel_id := <str>json_get(data, 'channel_id'),
  message_id := message_id,
  author_id := <str>json_get(data, 'author', 'id'),
  content := <str>json_get(data, 'content'),
  timestamp := <datetime>json_get(data, 'timestamp'),
  edited_timestamp := <datetime>json_get(data, 'edited_timestamp'),
}
unless conflict on ((.client, .message_id))
else (
  update discord::Message set {
    data := data,
    guild_id := <str>json_get(data, 'guild_id'),
    channel_id := <str>json_get(data, 'channel_id'),
    author_id := <str>json_get(data, 'author', 'id'),
    content := <str>json_get(data, 'content'),
    timestamp := <datetime>json_get(data, 'timestamp'),
    edited_timestamp := <datetime>json_get(data, 'edited_timestamp'),
  }
)
"""


class MessageMergeResult(BaseModel):
    id: UUID


adapter = TypeAdapter[MessageMergeResult | None](MessageMergeResult | None)


async def message_merge(
    executor: AsyncIOExecutor,
    *,
    message_id: str,
    data: Any,
) -> MessageMergeResult | None:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        message_id=message_id,
        data=orjson.dumps(data).decode(),
    )
    return adapter.validate_json(resp, strict=False)
