# Generated by gel-pydantic-codegen
# pyright: strict
from typing import NamedTuple
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  items := <array<tuple<message_id: str, noindex: str>>>$items,
for item in array_unpack(items)
union (
  update discord::Message
  filter .client = global client and .message_id = item.message_id
  set {
    noindex := item.noindex if item.noindex != '' else {}
  }
)
"""


class MessageBatchUpdateNoindexItems(NamedTuple):
    message_id: str
    noindex: str


class MessageBatchUpdateNoindexResult(BaseModel):
    id: UUID


adapter = TypeAdapter[list[MessageBatchUpdateNoindexResult]](list[MessageBatchUpdateNoindexResult])


async def message_batch_update_noindex(
    executor: AsyncIOExecutor,
    *,
    items: list[MessageBatchUpdateNoindexItems],
) -> list[MessageBatchUpdateNoindexResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        items=items,
    )
    return adapter.validate_json(resp, strict=False)
