# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  guild_id := <str>$guild_id,
  channel_ids := <array<str>>$channel_ids,
  messages := (
    select discord::Message
    filter .client = global client
    and .guild_id = guild_id
    and .channel_id in array_unpack(channel_ids)
  ),
  groups := (
    group messages
    using channel_id := .channel_id
    by channel_id
  )
select groups {
  channel_id := .key.channel_id,
  latest_timestamp := max(.elements.timestamp),
}
"""


class MessageSelectLatestTimestampsResult(BaseModel):
    channel_id: str
    latest_timestamp: datetime | None


adapter = TypeAdapter[list[MessageSelectLatestTimestampsResult]](
    list[MessageSelectLatestTimestampsResult]
)


async def message_select_latest_timestamps(
    executor: AsyncIOExecutor,
    *,
    guild_id: str,
    channel_ids: list[str],
) -> list[MessageSelectLatestTimestampsResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        guild_id=guild_id,
        channel_ids=channel_ids,
    )
    return adapter.validate_json(resp, strict=False)
