# Generated by gel-pydantic-codegen
# pyright: strict

from gel import AsyncIOExecutor
from pydantic import TypeAdapter

EDGEQL_QUERY = r"""
with
  messages := (
    select discord::Message
    filter .client = global client and not exists .deleted_at and not exists .pages
  )
select distinct messages.channel_id
"""


adapter = TypeAdapter[list[str]](list[str])


async def message_index_channels_filter_no_page(
    executor: AsyncIOExecutor,
) -> list[str]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
    )
    return adapter.validate_json(resp, strict=False)
