# Generated by gel-pydantic-codegen
# pyright: strict
from typing import Any
from uuid import UUID

import orjson
from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  message_id := <str>$message_id,
  data := <json>$data,
insert discord::Message {
  client := global client,
  message_id := message_id,
  data := data,
}
unless conflict on ((.client, .message_id))
else (
  update discord::Message set {
    data := data,
  }
)
"""


class MessageMergeResult(BaseModel):
    id: UUID


adapter = TypeAdapter[MessageMergeResult | None](MessageMergeResult | None)


async def message_merge(
    executor: AsyncIOExecutor,
    *,
    message_id: str,
    data: Any,
) -> MessageMergeResult | None:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        message_id=message_id,
        data=orjson.dumps(data).decode(),
    )
    return adapter.validate_json(resp, strict=False)
