# Generated by gel-pydantic-codegen
# pyright: strict
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  id := <uuid>$id,
delete discord::MessagePage
filter .id = id
"""


class PageDeleteResult(BaseModel):
    id: UUID


adapter = TypeAdapter[PageDeleteResult | None](PageDeleteResult | None)


async def page_delete(
    executor: AsyncIOExecutor,
    *,
    id: UUID,
) -> PageDeleteResult | None:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        id=id,
    )
    return adapter.validate_json(resp, strict=False)
