# Generated by gel-pydantic-codegen
# pyright: strict
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
delete discord::MessagePage filter .client = global client and not exists .messages
"""


class PageDeleteEmptyResult(BaseModel):
    id: UUID


adapter = TypeAdapter[list[PageDeleteEmptyResult]](list[PageDeleteEmptyResult])


async def page_delete_empty(
    executor: AsyncIOExecutor,
) -> list[PageDeleteEmptyResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
    )
    return adapter.validate_json(resp, strict=False)
