# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime
from typing import Any, NamedTuple

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
select ext::ai::search(discord::MessagePage {
  context,
  messages: { data, timestamp } order by .timestamp asc
}, <str>$search_query)
limit <optional int32>$limit
"""


class RagQueryResultObjectMessages(BaseModel):
    data: Any
    timestamp: datetime


class RagQueryResultObject(BaseModel):
    context: str
    messages: list[RagQueryResultObjectMessages]


class RagQueryResult(NamedTuple):
    object: RagQueryResultObject
    distance: float


adapter = TypeAdapter[list[RagQueryResult]](list[RagQueryResult])


async def rag_query(
    executor: AsyncIOExecutor,
    *,
    search_query: str,
    limit: int | None = None,
) -> list[RagQueryResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        search_query=search_query,
        limit=limit,
    )
    return adapter.validate_json(resp, strict=False)
