# Generated by gel-pydantic-codegen
# pyright: strict
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  message_ids := <array<str>>$message_ids,
delete discord::Reaction
filter .client = global client
and .message.message_id in array_unpack(message_ids)
"""


class ReactionBulkDeleteByMessageIdsResult(BaseModel):
    id: UUID


adapter = TypeAdapter[list[ReactionBulkDeleteByMessageIdsResult]](
    list[ReactionBulkDeleteByMessageIdsResult]
)


async def reaction_bulk_delete_by_message_ids(
    executor: AsyncIOExecutor,
    *,
    message_ids: list[str],
) -> list[ReactionBulkDeleteByMessageIdsResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        message_ids=message_ids,
    )
    return adapter.validate_json(resp, strict=False)
