# Generated by gel-pydantic-codegen
# pyright: strict
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  message_id := <str>$message_id,
  user_id := <str>$user_id,
  name := <str>$name,
  emoji_id := <optional str>$emoji_id,
  animated := <optional bool>$animated,
  burst := <optional bool>$burst,
  message := (select discord::Message filter .message_id = message_id and .client = global client),
  user := (select user::User filter .discord_id = user_id)
insert discord::Reaction {
  client := global client,
  message := message,
  user := user,
  name := name,
  emoji_id := emoji_id,
  animated := animated,
  burst := burst,
}
"""


class ReactionInsertResult(BaseModel):
    id: UUID


adapter = TypeAdapter[ReactionInsertResult](ReactionInsertResult)


async def reaction_insert(
    executor: AsyncIOExecutor,
    *,
    message_id: str,
    user_id: str,
    name: str,
    emoji_id: str | None = None,
    animated: bool | None = None,
    burst: bool | None = None,
) -> ReactionInsertResult:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        message_id=message_id,
        user_id=user_id,
        name=name,
        emoji_id=emoji_id,
        animated=animated,
        burst=burst,
    )
    return adapter.validate_json(resp, strict=False)
