# Generated by gel-pydantic-codegen
# pyright: strict
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  message_id := <str>$message_id,
  user_id := <optional str>$user_id,
  name := <optional str>$name,
  emoji_id := <optional str>$emoji_id,
delete discord::Reaction
filter .client = global client
and (.user.discord_id = user_id if exists user_id else true)
and (.name = name if exists name else true)
and (.emoji_id = emoji_id if exists emoji_id else true)
"""


class ReactionDeleteResult(BaseModel):
    id: UUID


adapter = TypeAdapter[list[ReactionDeleteResult]](list[ReactionDeleteResult])


async def reaction_delete(
    executor: AsyncIOExecutor,
    *,
    message_id: str,
    user_id: str | None = None,
    name: str | None = None,
    emoji_id: str | None = None,
) -> list[ReactionDeleteResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        message_id=message_id,
        user_id=user_id,
        name=name,
        emoji_id=emoji_id,
    )
    return adapter.validate_json(resp, strict=False)
