# Generated by gel-pydantic-codegen
# pyright: strict

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
select ai::Prompt {
  name,
  description,
}
filter .client = global client
"""


class PromptSelectNameDescResult(BaseModel):
    name: str
    description: str | None


adapter = TypeAdapter[list[PromptSelectNameDescResult]](list[PromptSelectNameDescResult])


async def prompt_select_name_desc(
    executor: AsyncIOExecutor,
) -> list[PromptSelectNameDescResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
    )
    return adapter.validate_json(resp, strict=False)
