# Generated by gel-pydantic-codegen
# pyright: strict
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
insert ai::Skill {
  client := global client,
  name := <str>$name,
  description := <str>$description,
  content := <str>$content,
}
"""


class SkillInsertResult(BaseModel):
    id: UUID


adapter = TypeAdapter[SkillInsertResult](SkillInsertResult)


async def skill_insert(
    executor: AsyncIOExecutor,
    *,
    name: str,
    description: str,
    content: str,
) -> SkillInsertResult:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        name=name,
        description=description,
        content=content,
    )
    return adapter.validate_json(resp, strict=False)
