# Generated by gel-pydantic-codegen
# pyright: strict
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
select ai::Skill { * } filter .client = global client
"""


class SkillSelectAllResult(BaseModel):
    id: UUID
    name: str
    content: str
    description: str


adapter = TypeAdapter[list[SkillSelectAllResult]](list[SkillSelectAllResult])


async def skill_select_all(
    executor: AsyncIOExecutor,
) -> list[SkillSelectAllResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
    )
    return adapter.validate_json(resp, strict=False)
