# Generated by gel-pydantic-codegen
# pyright: strict
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
delete ai::Skill filter .id = <uuid>$id
"""


class SkillDeleteByIdResult(BaseModel):
    id: UUID


adapter = TypeAdapter[SkillDeleteByIdResult | None](SkillDeleteByIdResult | None)


async def skill_delete_by_id(
    executor: AsyncIOExecutor,
    *,
    id: UUID,
) -> SkillDeleteByIdResult | None:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        id=id,
    )
    return adapter.validate_json(resp, strict=False)
