# Generated by gel-pydantic-codegen
# pyright: strict
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
insert user::User {
    discord_id := <str>$discord_id,
    age_verified := <bool>$age_verified,
    discord_username := <str>$discord_username,
}
unless conflict on .discord_id
else (
    update user::User set {
        age_verified := <bool>$age_verified,
        discord_username := <str>$discord_username,
    }
)
"""


class UserUpsertResult(BaseModel):
    id: UUID


adapter = TypeAdapter[UserUpsertResult](UserUpsertResult)


async def user_upsert(
    executor: AsyncIOExecutor,
    *,
    discord_id: str,
    age_verified: bool,
    discord_username: str,
) -> UserUpsertResult:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        discord_id=discord_id,
        age_verified=age_verified,
        discord_username=discord_username,
    )
    return adapter.validate_json(resp, strict=False)
