# Generated by gel-pydantic-codegen
# pyright: strict

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
select user::User {
  discord_id,
  discord_username,
  age_verified,
}
"""


class UserSelectResult(BaseModel):
    age_verified: bool
    discord_id: str
    discord_username: str


adapter = TypeAdapter[list[UserSelectResult]](list[UserSelectResult])


async def user_select(
    executor: AsyncIOExecutor,
) -> list[UserSelectResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
    )
    return adapter.validate_json(resp, strict=False)
