# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime
from enum import StrEnum
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  channel_id := <str>$channel_id,
  games := (
    select quizz::Game
    filter .client = global client and .quizz.channel_id = channel_id and .status = quizz::Status.STARTED
  )
select assert_single(games) {
  *,
  winner: {
    discord_id,
  },
  quizz: {
    *,
    author: {
      discord_id,
    },
  }
}
"""


class QuizzStatus(StrEnum):
    STARTED = 'STARTED'
    ENDED = 'ENDED'


class GameGetCurrentResultQuizzAuthor(BaseModel):
    discord_id: str


class GameGetCurrentResultQuizz(BaseModel):
    author: GameGetCurrentResultQuizzAuthor
    id: UUID
    channel_id: str
    answer: str | None
    attachment_url: str | None
    hints: list[str] | None
    question: str | None
    submitted_at: datetime


class GameGetCurrentResultWinner(BaseModel):
    discord_id: str


class GameGetCurrentResult(BaseModel):
    winner: GameGetCurrentResultWinner | None
    quizz: GameGetCurrentResultQuizz
    id: UUID
    message_id: str
    ended_at: datetime | None
    started_at: datetime
    status: QuizzStatus


adapter = TypeAdapter[GameGetCurrentResult | None](GameGetCurrentResult | None)


async def game_get_current(
    executor: AsyncIOExecutor,
    *,
    channel_id: str,
) -> GameGetCurrentResult | None:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        channel_id=channel_id,
    )
    return adapter.validate_json(resp, strict=False)
