# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime
from enum import StrEnum
from typing import Literal
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  status := <quizz::Status>$status,
select quizz::Game {
  *,
  winner: {
    discord_id,
  },
  quizz: {
    *,
    author: {
      discord_id,
    },
  }
}
filter .client = global client and .status = status
"""


GAME_SELECT_STATUS = Literal[
    'STARTED',
    'ENDED',
]


class QuizzStatus(StrEnum):
    ENDED = 'ENDED'
    STARTED = 'STARTED'


class GameSelectResultWinner(BaseModel):
    discord_id: str


class GameSelectResultQuizzAuthor(BaseModel):
    discord_id: str


class GameSelectResultQuizz(BaseModel):
    answer: str | None
    attachment_url: str | None
    author: GameSelectResultQuizzAuthor
    channel_id: str
    hints: list[str] | None
    id: UUID
    question: str | None
    submitted_at: datetime


class GameSelectResult(BaseModel):
    ended_at: datetime | None
    id: UUID
    message_id: str
    quizz: GameSelectResultQuizz
    started_at: datetime
    status: QuizzStatus
    winner: GameSelectResultWinner | None


adapter = TypeAdapter[list[GameSelectResult]](list[GameSelectResult])


async def game_select(
    executor: AsyncIOExecutor,
    *,
    status: GAME_SELECT_STATUS,
) -> list[GameSelectResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        status=status,
    )
    return adapter.validate_json(resp, strict=False)
