# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime
from enum import StrEnum
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  channel_id := <str>$channel_id,
select quizz::Game {
  *,
  winner: {
    discord_id,
  },
  quizz: {
    *,
    author: {
      discord_id,
    },
  }
}
filter .client = global client and .quizz.channel_id = channel_id and .status = quizz::Status.ENDED
order by .ended_at desc
limit 1
"""


class QuizzStatus(StrEnum):
    STARTED = 'STARTED'
    ENDED = 'ENDED'


class GameGetLastResultQuizzAuthor(BaseModel):
    discord_id: str


class GameGetLastResultQuizz(BaseModel):
    author: GameGetLastResultQuizzAuthor
    id: UUID
    channel_id: str
    answer: str | None
    attachment_url: str | None
    hints: list[str] | None
    question: str | None
    submitted_at: datetime


class GameGetLastResultWinner(BaseModel):
    discord_id: str


class GameGetLastResult(BaseModel):
    winner: GameGetLastResultWinner | None
    quizz: GameGetLastResultQuizz
    id: UUID
    message_id: str
    ended_at: datetime | None
    started_at: datetime
    status: QuizzStatus


adapter = TypeAdapter[GameGetLastResult | None](GameGetLastResult | None)


async def game_get_last(
    executor: AsyncIOExecutor,
    *,
    channel_id: str,
) -> GameGetLastResult | None:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        channel_id=channel_id,
    )
    return adapter.validate_json(resp, strict=False)
