# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime
from enum import StrEnum
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  id := <uuid>$id,
select quizz::Game {
  *,
  winner: {
    discord_id,
  },
  quizz: {
    *,
    author: {
      discord_id,
    },
  }
}
filter .id = id
"""


class QuizzStatus(StrEnum):
    ENDED = 'ENDED'
    STARTED = 'STARTED'


class GameGetByIdResultWinner(BaseModel):
    discord_id: str


class GameGetByIdResultQuizzAuthor(BaseModel):
    discord_id: str


class GameGetByIdResultQuizz(BaseModel):
    answer: str | None
    attachment_url: str | None
    author: GameGetByIdResultQuizzAuthor
    channel_id: str
    hints: list[str] | None
    id: UUID
    question: str | None
    submitted_at: datetime


class GameGetByIdResult(BaseModel):
    ended_at: datetime | None
    id: UUID
    message_id: str
    quizz: GameGetByIdResultQuizz
    started_at: datetime
    status: QuizzStatus
    winner: GameGetByIdResultWinner | None


adapter = TypeAdapter[GameGetByIdResult | None](GameGetByIdResult | None)


async def game_get_by_id(
    executor: AsyncIOExecutor,
    *,
    id: UUID,
) -> GameGetByIdResult | None:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        id=id,
    )
    return adapter.validate_json(resp, strict=False)
