# Generated by gel-pydantic-codegen
# pyright: strict
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  message_id := <str>$message_id
delete quizz::Game
filter .message_id = message_id
"""


class GameDeleteByMessageIdResult(BaseModel):
    id: UUID


adapter = TypeAdapter[GameDeleteByMessageIdResult | None](GameDeleteByMessageIdResult | None)


async def game_delete_by_message_id(
    executor: AsyncIOExecutor,
    *,
    message_id: str,
) -> GameDeleteByMessageIdResult | None:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        message_id=message_id,
    )
    return adapter.validate_json(resp, strict=False)
