# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime
from uuid import UUID

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
select reminder::Reminder {
  id,
  channel_id,
  message,
  timestamp,
  user: {
    discord_id,
  },
}
filter .client = global client
"""


class ReminderSelectAllResultUser(BaseModel):
    discord_id: str


class ReminderSelectAllResult(BaseModel):
    channel_id: str
    id: UUID
    message: str
    timestamp: datetime
    user: ReminderSelectAllResultUser


adapter = TypeAdapter[list[ReminderSelectAllResult]](list[ReminderSelectAllResult])


async def reminder_select_all(
    executor: AsyncIOExecutor,
) -> list[ReminderSelectAllResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
    )
    return adapter.validate_json(resp, strict=False)
