# Generated by gel-pydantic-codegen
# pyright: strict

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
select role::Role {
  role_id,
  emoji
}
filter .client = global client
"""


class RoleSelectAllResult(BaseModel):
    emoji: str
    role_id: str


adapter = TypeAdapter[list[RoleSelectAllResult]](list[RoleSelectAllResult])


async def role_select_all(
    executor: AsyncIOExecutor,
) -> list[RoleSelectAllResult]:
    resp = await executor.query_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
    )
    return adapter.validate_json(resp, strict=False)
