# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
    discord_id := <str>$discord_id,
    year_start := <datetime>$year_start,
    year_end := <datetime>$year_end,
    wasabi_messages := (
        select discord::Message
        filter
            .timestamp >= year_start
            and .timestamp < year_end
            and .content like '%[**Wasabi**]%'
            and .content like '%You received%character%'
            and <str>json_get(.data, 'mentions', '0', 'id') ?? '' = discord_id
    )
select {
    total_wasabi := count(wasabi_messages),
    contents := array_agg(wasabi_messages.content),
}
"""


class WrappedGetWasabiMessagesResult(BaseModel):
    contents: list[str]
    total_wasabi: int


adapter = TypeAdapter[WrappedGetWasabiMessagesResult](WrappedGetWasabiMessagesResult)


async def wrapped_get_wasabi_messages(
    executor: AsyncIOExecutor,
    *,
    discord_id: str,
    year_start: datetime,
    year_end: datetime,
) -> WrappedGetWasabiMessagesResult:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        discord_id=discord_id,
        year_start=year_start,
        year_end=year_end,
    )
    return adapter.validate_json(resp, strict=False)
