# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime
from enum import StrEnum

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  discord_id := <str>$discord_id,
  year_start := <datetime>$year_start,
  year_end := <datetime>$year_end,
  # Find player by discord_id and client
  player := (select waicolle::Player filter .user.discord_id = discord_id and .client = global client),
  # Free drop rolls (event + coupon) for this player in the year
  free_rolls := (
    select player.<author[is waicolle::RollOperation]
    filter
      .reason in {'event', 'coupon'}
      and .created_at >= year_start
      and .created_at < year_end
  )
select {
  event_count := count((select free_rolls filter .reason = 'event')),
  coupon_count := count((select free_rolls filter .reason = 'coupon')),
  # Return ranks as array - counting done in Python for performance
  ranks := array_agg(free_rolls.received.character.rank),
}
"""


class WaicolleRank(StrEnum):
    S = 'S'
    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'
    E = 'E'


class WrappedGetFreeStatsResult(BaseModel):
    event_count: int
    coupon_count: int
    ranks: list[WaicolleRank]


adapter = TypeAdapter[WrappedGetFreeStatsResult](WrappedGetFreeStatsResult)


async def wrapped_get_free_stats(
    executor: AsyncIOExecutor,
    *,
    discord_id: str,
    year_start: datetime,
    year_end: datetime,
) -> WrappedGetFreeStatsResult:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        discord_id=discord_id,
        year_start=year_start,
        year_end=year_end,
    )
    return adapter.validate_json(resp, strict=False)
