# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
    discord_id := <str>$discord_id,
    year_start := <datetime>$year_start,
    year_end := <datetime>$year_end,
    daily_tag_messages := (
        select discord::Message
        filter
            .timestamp >= year_start
            and .timestamp < year_end
            and .content like 'Rolling %'
            and .content like '%Daily tag%'
            and <str>json_get(.data, 'interaction', 'user', 'id') ?? '' = discord_id
    )
select {
    total_rolls := count(daily_tag_messages),
    contents := array_agg(daily_tag_messages.content),
}
"""


class WrappedGetDailyTagStatsResult(BaseModel):
    contents: list[str]
    total_rolls: int


adapter = TypeAdapter[WrappedGetDailyTagStatsResult](WrappedGetDailyTagStatsResult)


async def wrapped_get_daily_tag_stats(
    executor: AsyncIOExecutor,
    *,
    discord_id: str,
    year_start: datetime,
    year_end: datetime,
) -> WrappedGetDailyTagStatsResult:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        discord_id=discord_id,
        year_start=year_start,
        year_end=year_end,
    )
    return adapter.validate_json(resp, strict=False)
