# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime

from gel import AsyncIOExecutor
from pydantic import TypeAdapter

EDGEQL_QUERY = r"""
select count(
  discord::Message filter
    .author_id = <str>$discord_id
    and .timestamp >= <datetime>$year_start
    and .timestamp < <datetime>$year_end
)
"""


adapter = TypeAdapter[int](int)


async def wrapped_get_message_count(
    executor: AsyncIOExecutor,
    *,
    discord_id: str,
    year_start: datetime,
    year_end: datetime,
) -> int:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        discord_id=discord_id,
        year_start=year_start,
        year_end=year_end,
    )
    return adapter.validate_json(resp, strict=False)
