# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime
from enum import StrEnum

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  discord_id := <str>$discord_id,
  year_start := <datetime>$year_start,
  year_end := <datetime>$year_end,
  # Find player by discord_id and client
  player := (select waicolle::Player filter .user.discord_id = discord_id and .client = global client),
  # Random drop rolls for this player in the year (using backlink for efficiency)
  drop_rolls := (
    select player.<author[is waicolle::RollOperation]
    filter
      .reason = 'random'
      and .created_at >= year_start
      and .created_at < year_end
  )
select {
  total_drops := count(drop_rolls),
  # Return ranks as array - counting done in Python for performance
  ranks := array_agg(drop_rolls.received.character.rank),
}
"""


class WaicolleRank(StrEnum):
    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'
    E = 'E'
    S = 'S'


class WrappedGetDropStatsResult(BaseModel):
    ranks: list[WaicolleRank]
    total_drops: int


adapter = TypeAdapter[WrappedGetDropStatsResult](WrappedGetDropStatsResult)


async def wrapped_get_drop_stats(
    executor: AsyncIOExecutor,
    *,
    discord_id: str,
    year_start: datetime,
    year_end: datetime,
) -> WrappedGetDropStatsResult:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        discord_id=discord_id,
        year_start=year_start,
        year_end=year_end,
    )
    return adapter.validate_json(resp, strict=False)
