# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  year_start := <datetime>$year_start,
  year_end := <datetime>$year_end,
  messages := (
    select discord::Message
    filter .content ilike '%Conditional drop%'
       and .content ilike '%<@' ++ <str>$discord_id ++ '>%'
       and .timestamp >= year_start
       and .timestamp < year_end
  )
select {
  total := count(messages),
  contents := array_agg(messages.content),
}
"""


class WrappedGetConditionalStatsResult(BaseModel):
    total: int
    contents: list[str]


adapter = TypeAdapter[WrappedGetConditionalStatsResult](WrappedGetConditionalStatsResult)


async def wrapped_get_conditional_stats(
    executor: AsyncIOExecutor,
    *,
    year_start: datetime,
    year_end: datetime,
    discord_id: str,
) -> WrappedGetConditionalStatsResult:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        year_start=year_start,
        year_end=year_end,
        discord_id=discord_id,
    )
    return adapter.validate_json(resp, strict=False)
