# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  discord_id := <str>$discord_id,
  year_start := <datetime>$year_start,
  year_end := <datetime>$year_end,
  # Find player by discord_id and client
  player := (select waicolle::Player filter .user.discord_id = discord_id and .client = global client),
  # Reroll operations for this player in the year
  rerolls := (
    select player.<author[is waicolle::RerollOperation]
    filter
      .created_at >= year_start
      and .created_at < year_end
  )
select {
  total_rerolls := count(rerolls),
  total_rerolled := sum(count(rerolls.rerolled)),
  total_received := sum(count(rerolls.received)),
  # Single rerolls (exactly 1 waifu rerolled)
  single_rerolls := count((select rerolls filter count(.rerolled) = 1)),
  single_success := count((select rerolls filter count(.rerolled) = 1 and count(.received) = 1)),
}
"""


class WrappedGetRerollStatsResult(BaseModel):
    total_rerolls: int
    total_rerolled: int
    total_received: int
    single_rerolls: int
    single_success: int


adapter = TypeAdapter[WrappedGetRerollStatsResult](WrappedGetRerollStatsResult)


async def wrapped_get_reroll_stats(
    executor: AsyncIOExecutor,
    *,
    discord_id: str,
    year_start: datetime,
    year_end: datetime,
) -> WrappedGetRerollStatsResult:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        discord_id=discord_id,
        year_start=year_start,
        year_end=year_end,
    )
    return adapter.validate_json(resp, strict=False)
