# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  discord_id := <str>$discord_id,
  year_start := <datetime>$year_start,
  year_end := <datetime>$year_end,
  # Find player by discord_id and client
  player := (select waicolle::Player filter .user.discord_id = discord_id and .client = global client),
  # Paid rolls (A-H + daily/weekly) for this player in the year
  paid_rolls := (
    select player.<author[is waicolle::RollOperation]
    filter
      .reason in {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'daily', 'weekly'}
      and .created_at >= year_start
      and .created_at < year_end
  )
select {
  total_rolls := count(paid_rolls),
  total_moecoins := sum(paid_rolls.moecoins),
  total_waifus := count(paid_rolls.received),
  # Return reasons as array - counting done in Python for performance
  reasons := array_agg(paid_rolls.reason),
}
"""


class WrappedGetRollStatsResult(BaseModel):
    reasons: list[str]
    total_moecoins: int
    total_rolls: int
    total_waifus: int


adapter = TypeAdapter[WrappedGetRollStatsResult](WrappedGetRollStatsResult)


async def wrapped_get_roll_stats(
    executor: AsyncIOExecutor,
    *,
    discord_id: str,
    year_start: datetime,
    year_end: datetime,
) -> WrappedGetRollStatsResult:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        discord_id=discord_id,
        year_start=year_start,
        year_end=year_end,
    )
    return adapter.validate_json(resp, strict=False)
