# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  year_start := <datetime>$year_start,
  year_end := <datetime>$year_end,
  community_messages := (
    select discord::Message
    filter .author_id != <str>$discord_id
       and .timestamp >= year_start
       and .timestamp < year_end
       and len(.content) > 0
    limit 50000
  )
select {
  community_contents := array_agg(community_messages.content),
}
"""


class WrappedGetCommunityWordsResult(BaseModel):
    community_contents: list[str]


adapter = TypeAdapter[WrappedGetCommunityWordsResult](WrappedGetCommunityWordsResult)


async def wrapped_get_community_words(
    executor: AsyncIOExecutor,
    *,
    year_start: datetime,
    year_end: datetime,
    discord_id: str,
) -> WrappedGetCommunityWordsResult:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        year_start=year_start,
        year_end=year_end,
        discord_id=discord_id,
    )
    return adapter.validate_json(resp, strict=False)
