# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime
from enum import StrEnum

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
    discord_id := <str>$discord_id,
    year_start := <datetime>$year_start,
    year_end := <datetime>$year_end,
    # Find player by discord_id and client (uses backlink for efficiency)
    player := (select waicolle::Player filter .user.discord_id = discord_id and .client = global client),
    wasabi_rolls := (
        select player.<author[is waicolle::RollOperation]
        filter
            .created_at >= year_start
            and .created_at < year_end
            and .reason = 'wasabi'
    )
select {
    total_rolls := count(wasabi_rolls),
    ranks := array_agg(wasabi_rolls.received.character.rank),
}
"""


class WaicolleRank(StrEnum):
    S = 'S'
    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'
    E = 'E'


class WrappedGetWasabiStatsResult(BaseModel):
    total_rolls: int
    ranks: list[WaicolleRank]


adapter = TypeAdapter[WrappedGetWasabiStatsResult](WrappedGetWasabiStatsResult)


async def wrapped_get_wasabi_stats(
    executor: AsyncIOExecutor,
    *,
    discord_id: str,
    year_start: datetime,
    year_end: datetime,
) -> WrappedGetWasabiStatsResult:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        discord_id=discord_id,
        year_start=year_start,
        year_end=year_end,
    )
    return adapter.validate_json(resp, strict=False)
