# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  discord_id := <str>$discord_id,
  year_start := <datetime>$year_start,
  year_end := <datetime>$year_end,
  messages := (
    select discord::Message
    filter
      .author_id = discord_id
      and .timestamp >= year_start
      and .timestamp < year_end
  ),
  link_messages := (
    select messages
    filter re_test('https?://', .content)
  )
select {
  total_link_count := count(link_messages),
  # YouTube (youtube.com, youtu.be)
  youtube_count := count(
    link_messages filter re_test('https?://(www\\.)?(youtube\\.com|youtu\\.be)', .content)
  ),
  # Twitter/X (x.com, twitter.com, vxtwitter, fixupx, fxtwitter, fixvx)
  twitter_count := count(
    link_messages filter re_test('https?://(www\\.)?(x\\.com|twitter\\.com|vxtwitter\\.com|fixupx\\.com|fxtwitter\\.com|fixvx\\.com|girlcockx\\.com)', .content)
  ),
  # Reddit (reddit.com, vxreddit)
  reddit_count := count(
    link_messages filter re_test('https?://(www\\.)?(reddit\\.com|vxreddit\\.com|old\\.reddit\\.com)', .content)
  ),
  # Bluesky
  bluesky_count := count(
    link_messages filter re_test('https?://(www\\.)?bsky\\.app', .content)
  ),
  # Tenor (GIFs)
  tenor_count := count(
    link_messages filter re_test('https?://(www\\.)?tenor\\.com', .content)
  ),
  # Discord
  discord_count := count(
    link_messages filter re_test('https?://(www\\.)?(discord\\.com|cdn\\.discordapp\\.com|media\\.discordapp\\.net)', .content)
  ),
  # GitHub
  github_count := count(
    link_messages filter re_test('https?://(www\\.)?github\\.com', .content)
  ),
  # AniList
  anilist_count := count(
    link_messages filter re_test('https?://(www\\.)?anilist\\.co', .content)
  ),
  # Instagram
  instagram_count := count(
    link_messages filter re_test('https?://(www\\.)?(instagram\\.com|kkinstagram\\.com|ddinstagram\\.com)', .content)
  ),
  # Wikipedia
  wikipedia_count := count(
    link_messages filter re_test('https?://[a-z]{2}\\.wikipedia\\.org', .content)
  ),
  # Steam
  steam_count := count(
    link_messages filter re_test('https?://(www\\.)?store\\.steampowered\\.com', .content)
  ),
}
"""


class WrappedGetLinkStatsResult(BaseModel):
    total_link_count: int
    youtube_count: int
    twitter_count: int
    reddit_count: int
    bluesky_count: int
    tenor_count: int
    discord_count: int
    github_count: int
    anilist_count: int
    instagram_count: int
    wikipedia_count: int
    steam_count: int


adapter = TypeAdapter[WrappedGetLinkStatsResult](WrappedGetLinkStatsResult)


async def wrapped_get_link_stats(
    executor: AsyncIOExecutor,
    *,
    discord_id: str,
    year_start: datetime,
    year_end: datetime,
) -> WrappedGetLinkStatsResult:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        discord_id=discord_id,
        year_start=year_start,
        year_end=year_end,
    )
    return adapter.validate_json(resp, strict=False)
