# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  discord_id := <str>$discord_id,
  year_start := <datetime>$year_start,
  year_end := <datetime>$year_end,
  # Find all wordle result messages
  wordle_messages := (
    select discord::Message {
      content,
      timestamp
    }
    filter
      .timestamp >= year_start
      and .timestamp < year_end
      and .content ilike "**Your group is on a%"
  )
select {
  messages := wordle_messages {
    content,
    timestamp
  },
  discord_id_pattern := '<@' ++ discord_id ++ '>',
}
"""


class WrappedGetWordleStatsResultMessages(BaseModel):
    content: str
    timestamp: datetime


class WrappedGetWordleStatsResult(BaseModel):
    messages: list[WrappedGetWordleStatsResultMessages]
    discord_id_pattern: str


adapter = TypeAdapter[WrappedGetWordleStatsResult](WrappedGetWordleStatsResult)


async def wrapped_get_wordle_stats(
    executor: AsyncIOExecutor,
    *,
    discord_id: str,
    year_start: datetime,
    year_end: datetime,
) -> WrappedGetWordleStatsResult:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        discord_id=discord_id,
        year_start=year_start,
        year_end=year_end,
    )
    return adapter.validate_json(resp, strict=False)
