# Generated by gel-pydantic-codegen
# pyright: strict
from datetime import datetime

from gel import AsyncIOExecutor
from pydantic import BaseModel, TypeAdapter

EDGEQL_QUERY = r"""
with
  year_start := <datetime>$year_start,
  year_end := <datetime>$year_end,
  user_messages := (
    select discord::Message
    filter .author_id = <str>$discord_id
       and .timestamp >= year_start
       and .timestamp < year_end
       and len(.content) > 0
  )
select {
  user_contents := array_agg(user_messages.content),
}
"""


class WrappedGetUserWordsResult(BaseModel):
    user_contents: list[str]


adapter = TypeAdapter[WrappedGetUserWordsResult](WrappedGetUserWordsResult)


async def wrapped_get_user_words(
    executor: AsyncIOExecutor,
    *,
    year_start: datetime,
    year_end: datetime,
    discord_id: str,
) -> WrappedGetUserWordsResult:
    resp = await executor.query_single_json(  # pyright: ignore[reportUnknownMemberType]
        EDGEQL_QUERY,
        year_start=year_start,
        year_end=year_end,
        discord_id=discord_id,
    )
    return adapter.validate_json(resp, strict=False)
